"""Compose and send the daily digest email."""
from __future__ import annotations

import logging
from collections import defaultdict
from datetime import datetime
from pathlib import Path

from accounts import display_name
from gmail_client import GmailClient, send_message
from stats import compute_stats, hbar

log = logging.getLogger("digest")


def send_digest(
    *,
    from_account: str,
    to_address: str,
    summary: dict[str, int],
    classified: list[dict],
    tracker_path: Path,
) -> None:
    today = datetime.now().strftime("%a %b %d, %Y")
    subject = f"Job tracker — {today} ({summary['new']} new, {summary['updated']} updated)"

    stats = compute_stats(tracker_path)
    stats_html = _render_stats_html(stats)
    activity_html = _render_activity_html(classified)
    by_account_today_html = _render_by_account_today(classified, stats)

    html = f"""<html><body style="font-family:-apple-system,system-ui,Arial,sans-serif;color:#111;max-width:760px;">
<h2 style="margin-bottom:4px;">Job tracker — {today}</h2>
<p style="color:#555;margin-top:0;">
  {summary['new']} new row(s), {summary['updated']} updated, {summary['skipped']} skipped.
  Full tracker attached.
</p>

<h3 style="margin-top:24px;margin-bottom:8px;">Today's activity</h3>
{activity_html}

{by_account_today_html}

{stats_html}

<hr style="margin-top:32px;border:none;border-top:1px solid #ddd;">
<p style="color:#888;font-size:12px;">
  Auto-generated by job-tracker. Response/interview/rejection rates are
  computed against applications older than {stats['response_window_days']} days
  ({stats['mature_count']} of {stats['total']} total) — younger applications
  haven't had a fair chance to receive a response yet.
</p>
</body></html>"""

    client = GmailClient(from_account)
    send_message(
        client,
        to=to_address,
        subject=subject,
        html_body=html,
        attachments=[tracker_path] if tracker_path.exists() else [],
    )


# --- stats panel -------------------------------------------------------------

def _render_stats_html(s: dict) -> str:
    if s["total"] == 0:
        return "<p style='color:#666;'>No applications tracked yet.</p>"

    avg_resp = (
        f"{s['avg_response_days']} days"
        if s['avg_response_days'] is not None
        else "—"
    )

    counters = f"""
<div style="display:flex;gap:12px;margin-top:8px;flex-wrap:wrap;">
  {_counter_card('Total applied', s['total'])}
  {_counter_card('This week', s['this_week'])}
  {_counter_card('This month', s['this_month'])}
  {_counter_card('Avg response', avg_resp)}
</div>
"""

    mature = s['mature_count']
    if mature > 0:
        rate_rows = (
            _bar_row("Response rate", s['response_rate'], 100)
            + _bar_row("Interview rate", s['interview_rate'], 100)
            + _bar_row("Rejection rate", s['rejection_rate'], 100)
        )
        rates_block = f"""
<h4 style="margin-top:16px;margin-bottom:6px;color:#444;">
  Rates <span style="font-weight:normal;color:#888;font-size:13px;">
  (of {mature} mature application{'s' if mature != 1 else ''})</span>
</h4>
<table style="border-collapse:collapse;font-size:14px;">{rate_rows}</table>
"""
    else:
        rates_block = (
            f"<p style='color:#888;font-size:13px;margin-top:12px;'>"
            f"Rates will appear once you have applications older than "
            f"{s['response_window_days']} days.</p>"
        )

    top_block = ""
    if s["top_companies"]:
        max_n = s["top_companies"][0][1]
        top_rows = "".join(
            _bar_row(name, n, max_n, value_fmt=str(n))
            for name, n in s["top_companies"]
        )
        top_block = f"""
<h4 style="margin-top:16px;margin-bottom:6px;color:#444;">Top companies (by # of applications)</h4>
<table style="border-collapse:collapse;font-size:14px;">{top_rows}</table>
"""

    acct_block = ""  # moved out into its own dedicated _render_by_account_today section

    return f"""
<div style="border:1px solid #e5e7eb;border-radius:8px;padding:16px;background:#fafbfc;margin-top:16px;">
<h3 style="margin-top:0;margin-bottom:8px;">📊 Stats</h3>
{counters}
{rates_block}
{top_block}
{acct_block}
</div>
"""


def _counter_card(label: str, value) -> str:
    return (
        "<div style='flex:1;min-width:120px;background:#fff;border:1px solid #e5e7eb;"
        "border-radius:6px;padding:10px 12px;'>"
        f"<div style='color:#666;font-size:12px;text-transform:uppercase;letter-spacing:0.04em;'>{_esc(label)}</div>"
        f"<div style='color:#111;font-size:22px;font-weight:600;margin-top:2px;'>{_esc(str(value))}</div>"
        "</div>"
    )


def _bar_row(label: str, value: float, scale: float, *, value_fmt: str | None = None) -> str:
    bar = hbar(value, scale, width=22)
    display = value_fmt if value_fmt is not None else f"{value:.1f}%"
    return (
        "<tr>"
        f"<td style='padding:3px 10px 3px 0;color:#444;'>{_esc(label)}</td>"
        f"<td style='padding:3px 10px;font-family:ui-monospace,Menlo,monospace;color:#1f4e78;'>{bar}</td>"
        f"<td style='padding:3px 0;color:#111;font-variant-numeric:tabular-nums;'>{_esc(display)}</td>"
        "</tr>"
    )


# --- today's activity tables ------------------------------------------------

def _render_activity_html(classified: list[dict]) -> str:
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for c in classified:
        by_cat[c["category"]].append(c)

    sections_html = []
    section_order = [
        ("offer", "🎉 Offers"),
        ("interview", "📞 Interviews"),
        ("rejected", "❌ Rejections"),
        ("applied", "📝 Applications submitted"),
    ]
    for key, title in section_order:
        items = by_cat.get(key, [])
        if not items:
            continue
        rows = "".join(_row_html(c) for c in items)
        sections_html.append(
            f"<h4 style='margin-top:20px;margin-bottom:6px;'>{title} ({len(items)})</h4>"
            "<table style='border-collapse:collapse;width:100%;font-size:14px;'>"
            "<thead><tr style='background:#f3f4f6;text-align:left;'>"
            "<th style='padding:6px 8px;'>Company</th>"
            "<th style='padding:6px 8px;'>Role</th>"
            "<th style='padding:6px 8px;'>Account</th>"
            "<th style='padding:6px 8px;'>Why</th>"
            f"</tr></thead><tbody>{rows}</tbody></table>"
        )

    if not sections_html:
        return "<p>No job-related activity in the last 24 hours.</p>"
    return "".join(sections_html)


def _row_html(c: dict) -> str:
    return (
        "<tr style='border-bottom:1px solid #eee;'>"
        f"<td style='padding:6px 8px;'>{_esc(c.get('company') or '(unknown)')}</td>"
        f"<td style='padding:6px 8px;'>{_esc(c.get('role') or '—')}</td>"
        f"<td style='padding:6px 8px;color:#666;'>{_esc(display_name(c.get('account', '')))}</td>"
        f"<td style='padding:6px 8px;color:#444;'>{_esc(c.get('reason', ''))}</td>"
        "</tr>"
    )


# --- per-account "today" + lifetime breakdown -------------------------------

def _render_by_account_today(classified: list[dict], stats: dict) -> str:
    """Per-account table showing today's applied/rejected counts side-by-side
    with lifetime totals. Includes accounts with zero activity today.
    """
    import os

    # All configured accounts from the env var — this is the source of truth
    # for "show every account always," even those with no rows yet.
    raw = os.environ.get("GMAIL_ACCOUNTS", "")
    all_labels = [a.strip() for a in raw.split(",") if a.strip()]

    # Today's counts from the classified list passed into this run
    today_applied: dict[str, int] = defaultdict(int)
    today_rejected: dict[str, int] = defaultdict(int)
    for c in classified:
        acct = c.get("account", "")
        if c.get("category") == "applied":
            today_applied[acct] += 1
        elif c.get("category") == "rejected":
            today_rejected[acct] += 1

    # Lifetime per-account from stats
    lifetime = stats.get("by_account", {})

    # Make sure any account that appears in classified or lifetime but not
    # in the env var still gets a row (defensive against config drift).
    labels = list(all_labels)
    for extra in list(today_applied.keys()) + list(today_rejected.keys()) + list(lifetime.keys()):
        if extra and extra not in labels:
            labels.append(extra)

    if not labels:
        return ""

    # Sort: most active today first, then by lifetime applied, then alpha
    def sort_key(label: str) -> tuple:
        today_total = today_applied.get(label, 0) + today_rejected.get(label, 0)
        life = lifetime.get(label, {})
        life_total = life.get("applied", 0) + life.get("rejected", 0)
        return (-today_total, -life_total, display_name(label).lower())

    labels.sort(key=sort_key)

    rows = ""
    for label in labels:
        ta = today_applied.get(label, 0)
        tr = today_rejected.get(label, 0)
        life = lifetime.get(label, {})
        la = life.get("applied", 0)
        lr = life.get("rejected", 0)

        # Soften zero values so the eye lands on what actually happened
        def cell(value: int, *, color: str = "#111") -> str:
            if value == 0:
                return f"<td style='padding:6px 10px;color:#bbb;'>0</td>"
            return f"<td style='padding:6px 10px;color:{color};font-weight:500;'>{value}</td>"

        rows += (
            "<tr style='border-bottom:1px solid #eee;'>"
            f"<td style='padding:6px 10px;font-weight:500;'>{_esc(display_name(label))}</td>"
            f"{cell(ta, color='#1f4e78')}"
            f"{cell(tr, color='#a33')}"
            f"{cell(la, color='#1f4e78')}"
            f"{cell(lr, color='#a33')}"
            "</tr>"
        )

    return f"""
<h3 style="margin-top:32px;margin-bottom:8px;">📧 By Gmail account</h3>
<table style="border-collapse:collapse;width:100%;font-size:14px;">
  <thead>
    <tr style="background:#f3f4f6;text-align:left;">
      <th rowspan="2" style="padding:8px 10px;vertical-align:bottom;">Account</th>
      <th colspan="2" style="padding:6px 10px 2px;border-bottom:1px solid #ddd;text-align:center;">Today</th>
      <th colspan="2" style="padding:6px 10px 2px;border-bottom:1px solid #ddd;text-align:center;">Lifetime</th>
    </tr>
    <tr style="background:#f3f4f6;">
      <th style="padding:4px 10px 6px;font-weight:500;color:#444;">Applied</th>
      <th style="padding:4px 10px 6px;font-weight:500;color:#444;">Rejected</th>
      <th style="padding:4px 10px 6px;font-weight:500;color:#444;">Applied</th>
      <th style="padding:4px 10px 6px;font-weight:500;color:#444;">Rejected</th>
    </tr>
  </thead>
  <tbody>{rows}</tbody>
</table>
"""


def _esc(s) -> str:
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))